# Generated by Django 4.1.7 on 2023-04-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewquestion',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='category',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('CNND', 'CNND')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='difficulty_level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='question_text',
            field=models.TextField(null=True),
        ),
    ]
